### ISSUE TITLE
Dashboard fails with "Templating init failed Datasource named local carbon api was not found"

### ISSUE THREAD

**Issue by mb-1408-de** [plz/E-Series-Graphite-Grafana#7]
Could fix it with this little patch. 

`--- "Volume Detail.json"	2017-02-22 11:17:31.000000000 +0100
+++ "Volume Detail_mbk.json"	2017-04-06 17:01:25.380729009 +0200
@@ -765,7 +765,7 @@
             "$__all"
           ]
         },
-        "datasource": "local carbon api",
+        "datasource": null,
         "hide": 0,
         "includeAll": true,
         "label": null,`

**Comment by plz** [comment]
Thanks for the patch, indeed thats a local reference that needed to be removed. Thanks @mb-1408-de !

Fixed with https://github.com/plz/E-Series-Graphite-Grafana/commit/4b098d9024d643eae575bf71c092740b236dfd76
